// install the "REST Client" extension in VSCode.
GET http://localhost:3000/coffeeorders HTTP/1.1

###

POST http://localhost:3000/coffeeorders HTTP/1.1
content-type: application/json

{
    "coffee": "Richard Stanley",
    "email": "audstanley@gmail.com",
    "flavor": "Pumpkin Spice",
    "strength": "100"
}

###

# deletes all the orders from the collection
DELETE http://localhost:3000/coffeeorders HTTP/1.1

###

GET http://localhost:3000/coffeeorders/audstanley@gmail.com HTTP/1.1

###

PUT http://localhost:3000/coffeeorders/audstanley@gmail.com HTTP/1.1
content-type: application/json

{
    "coffee": "Richard Stanley",
    "email": "audstanley@gmail.com",
    "flavor": "Vanilla",
    "strength": "0"
}

###

# only delete audstanley's last order
DELETE http://localhost:3000/coffeeorders/audstanley@gmail.com HTTP/1.1
